### ISSUE TITLE
need update deps and refactor

### ISSUE THREAD

**Issue by elycheikhsmail** [asad-mlbd/deno-api-starter-oak#11]
I think this is a good example and give complete how to work with oak in real project. but I think if move remove nessie from deps this project will more stable, we can use denSqlBuilder i stead.
and I'd like to update oak version to the katest.

**Comment by asad-devx** [comment]
Hello @elycheikhsmail . Thanks for you interest. 

Would be great if  you  can give a PR updating the oak, and other dependent versions.

Regarding add `denSqlBuilder` - let me think and get back to you.
