### ISSUE TITLE
How can add middlewares to redirect to different Routes? 

### ISSUE THREAD

**Issue by sameeerkashyap** [asad-mlbd/deno-api-starter-oak#8]
I want to add middlewares which are equivalent to this in Express.js.

```
app.use('/user', userRoutes);
app.use('/post', postRoutes);
```
I tired a couple of things like exporting route object but this didn't work. 

Right now I have two different route objects instantiated in two files. Which I know isn't the best. 

So I was confused about how to achieve the same as above in Oak. 

would love some clarifications. Thank you

**Comment by Sameerkash** [comment]
and also I'm not able to attach the user to Context as you do in JwtMiddleare. What am I missing?

**Comment by sameeerkashyap** [comment]
Any solution to this ?

**Comment by asad-devx** [comment]
@Sameerkash I think it is still on enhancement list 
https://github.com/oakserver/oak/issues/6

**Comment by sameeerkashyap** [comment]
Okay thanks for pointing out! Will follow the issue!
